
package de.budget.onlinebudget;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BudgetOnlineServiceBeanService", targetNamespace = "http://onlinebudget.budget.de/", wsdlLocation = "http://localhost:8080/budget/BudgetOnlineServiceBean?wsdl")
public class BudgetOnlineServiceBeanService
    extends Service
{

    private final static URL BUDGETONLINESERVICEBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException BUDGETONLINESERVICEBEANSERVICE_EXCEPTION;
    private final static QName BUDGETONLINESERVICEBEANSERVICE_QNAME = new QName("http://onlinebudget.budget.de/", "BudgetOnlineServiceBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/budget/BudgetOnlineServiceBean?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUDGETONLINESERVICEBEANSERVICE_WSDL_LOCATION = url;
        BUDGETONLINESERVICEBEANSERVICE_EXCEPTION = e;
    }

    public BudgetOnlineServiceBeanService() {
        super(__getWsdlLocation(), BUDGETONLINESERVICEBEANSERVICE_QNAME);
    }

    public BudgetOnlineServiceBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BUDGETONLINESERVICEBEANSERVICE_QNAME, features);
    }

    public BudgetOnlineServiceBeanService(URL wsdlLocation) {
        super(wsdlLocation, BUDGETONLINESERVICEBEANSERVICE_QNAME);
    }

    public BudgetOnlineServiceBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BUDGETONLINESERVICEBEANSERVICE_QNAME, features);
    }

    public BudgetOnlineServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BudgetOnlineServiceBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BudgetOnlineServiceBean
     */
    @WebEndpoint(name = "BudgetOnlineServiceBeanPort")
    public BudgetOnlineServiceBean getBudgetOnlineServiceBeanPort() {
        return super.getPort(new QName("http://onlinebudget.budget.de/", "BudgetOnlineServiceBeanPort"), BudgetOnlineServiceBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BudgetOnlineServiceBean
     */
    @WebEndpoint(name = "BudgetOnlineServiceBeanPort")
    public BudgetOnlineServiceBean getBudgetOnlineServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://onlinebudget.budget.de/", "BudgetOnlineServiceBeanPort"), BudgetOnlineServiceBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUDGETONLINESERVICEBEANSERVICE_EXCEPTION!= null) {
            throw BUDGETONLINESERVICEBEANSERVICE_EXCEPTION;
        }
        return BUDGETONLINESERVICEBEANSERVICE_WSDL_LOCATION;
    }

}
