
package de.budget.onlinebudget;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BudgetOnlineException", targetNamespace = "http://onlinebudget.budget.de/")
public class BudgetOnlineException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BudgetOnlineException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BudgetOnlineException_Exception(String message, BudgetOnlineException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BudgetOnlineException_Exception(String message, BudgetOnlineException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.budget.onlinebudget.BudgetOnlineException
     */
    public BudgetOnlineException getFaultInfo() {
        return faultInfo;
    }

}
